apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythontest
  labels:
    app: pythontest
spec:
  selector:
    matchLabels:
      app: pythontest
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: pythontest
    spec:
      containers:
        - image: host.minikube.internal:4000/pythontest:latest
          name: pythontest
          ports:
            - containerPort: 5000
              name: microport